from aoc_2024 import day8

test_data = day8.parse("""............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""")


def test_day8():
    assert day8.part1(*test_data) == 14
    assert day8.part2(*test_data) == 34
