from aoc_2023 import day11

test_data = day11.parse("""...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....""")


def test_day11():
    assert day11.part1(test_data) == 374
    assert day11.part2(test_data, 10) == 1030
